GET http://localhost:4000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjM0NTA5LTYzMDEtNGRlZC1hMTQwLTU3ZTQ3NTQ3ZjEzOSIsImZpcnN0bmFtZSI6IkRvZSIsImxhc3RuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzUzMjA5MTgsImV4cCI6MTY3NTQwNzMxOH0.ncoEfmsknjeiQ4juatwVuLTvCFh3nibf7wHXUmF-5KU
 
###
GET http://localhost:4000/dWLVO5wmZ
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjM0NTA5LTYzMDEtNGRlZC1hMTQwLTU3ZTQ3NTQ3ZjEzOSIsImZpcnN0bmFtZSI6IkRvZSIsImxhc3RuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzUzMjA5MTgsImV4cCI6MTY3NTQwNzMxOH0.ncoEfmsknjeiQ4juatwVuLTvCFh3nibf7wHXUmF-5KU


###
GET http://localhost:4000/users/ec11242e-8203-427f-8ef8-236a47bb0307/parcels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjM0NTA5LTYzMDEtNGRlZC1hMTQwLTU3ZTQ3NTQ3ZjEzOSIsImZpcnN0bmFtZSI6IkRvZSIsImxhc3RuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzUzMjA5MTgsImV4cCI6MTY3NTQwNzMxOH0.ncoEfmsknjeiQ4juatwVuLTvCFh3nibf7wHXUmF-5KU

###
GET http://localhost:4000/users/ec11242e-8203-427f-8ef8-236a47bb0307/parcels/sent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjM0NTA5LTYzMDEtNGRlZC1hMTQwLTU3ZTQ3NTQ3ZjEzOSIsImZpcnN0bmFtZSI6IkRvZSIsImxhc3RuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzUzMjA5MTgsImV4cCI6MTY3NTQwNzMxOH0.ncoEfmsknjeiQ4juatwVuLTvCFh3nibf7wHXUmF-5KU
###
GET http://localhost:4000/users/ec11242e-8203-427f-8ef8-236a47bb0307/parcels/received
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjM0NTA5LTYzMDEtNGRlZC1hMTQwLTU3ZTQ3NTQ3ZjEzOSIsImZpcnN0bmFtZSI6IkRvZSIsImxhc3RuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzUzMjA5MTgsImV4cCI6MTY3NTQwNzMxOH0.ncoEfmsknjeiQ4juatwVuLTvCFh3nibf7wHXUmF-5KU

###
POST http://localhost:4000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjM0NTA5LTYzMDEtNGRlZC1hMTQwLTU3ZTQ3NTQ3ZjEzOSIsImZpcnN0bmFtZSI6IkRvZSIsImxhc3RuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzUzMjA5MTgsImV4cCI6MTY3NTQwNzMxOH0.ncoEfmsknjeiQ4juatwVuLTvCFh3nibf7wHXUmF-5KU

{
    "sender": "d17ddf1d-f073-4b96-b37b-7e1b455c2748",
     "recepient": "ec11242e-8203-427f-8ef8-236a47bb0307",
     "_from": "Nyeri",
     "destination":"Karatina",
     "weight":8.0,
     "price": 500,
     "status":"onTransit"
}

###
PUT  http://localhost:4000/134
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjM0NTA5LTYzMDEtNGRlZC1hMTQwLTU3ZTQ3NTQ3ZjEzOSIsImZpcnN0bmFtZSI6IkRvZSIsImxhc3RuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzUzMjA5MTgsImV4cCI6MTY3NTQwNzMxOH0.ncoEfmsknjeiQ4juatwVuLTvCFh3nibf7wHXUmF-5KU

{
     "sender": "d17ddf1d-f073-4b96-b37b-7e1b455c2748",
     "recepient": "ec11242e-8203-427f-8ef8-236a47bb0307",
     "_from": "Nairobi",
     "destination":"Karatina",
     "weight":8.0,
     "price": 500,
     "status":"onTransit"
}

###
DELETE   http://localhost:4000/dWLVO5wmZ
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjM0NTA5LTYzMDEtNGRlZC1hMTQwLTU3ZTQ3NTQ3ZjEzOSIsImZpcnN0bmFtZSI6IkRvZSIsImxhc3RuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzUzMjA5MTgsImV4cCI6MTY3NTQwNzMxOH0.ncoEfmsknjeiQ4juatwVuLTvCFh3nibf7wHXUmF-5KU

###
GET http://localhost:4000/profile/parcels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjM0NTA5LTYzMDEtNGRlZC1hMTQwLTU3ZTQ3NTQ3ZjEzOSIsImZpcnN0bmFtZSI6IkRvZSIsImxhc3RuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzUzMjA5MTgsImV4cCI6MTY3NTQwNzMxOH0.ncoEfmsknjeiQ4juatwVuLTvCFh3nibf7wHXUmF-5KU

###
GET http://localhost:4000/profile/parcels/sent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjM0NTA5LTYzMDEtNGRlZC1hMTQwLTU3ZTQ3NTQ3ZjEzOSIsImZpcnN0bmFtZSI6IkRvZSIsImxhc3RuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzUzMjA5MTgsImV4cCI6MTY3NTQwNzMxOH0.ncoEfmsknjeiQ4juatwVuLTvCFh3nibf7wHXUmF-5KU

###
GET http://localhost:4000/profile/parcels/received
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImExNjM0NTA5LTYzMDEtNGRlZC1hMTQwLTU3ZTQ3NTQ3ZjEzOSIsImZpcnN0bmFtZSI6IkRvZSIsImxhc3RuYW1lIjoiSm9obiIsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzUzMjA5MTgsImV4cCI6MTY3NTQwNzMxOH0.ncoEfmsknjeiQ4juatwVuLTvCFh3nibf7wHXUmF-5KU