GET http://localhost:4000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxN2RkZjFkLWYwNzMtNGI5Ni1iMzdiLTdlMWI0NTVjMjc0OCIsImZpcnN0bmFtZSI6IkVyaWNhIiwibGFzdG5hbWUiOiJlcmljYSIsImVtYWlsIjoid2FuQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU2Nzg5IiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY3MjkyNTQzNywiZXhwIjoxNjczMDExODM3fQ.OeydOe5p9lLoNj7tVN1GYASoiktmXNDYrKT5NBE7Ng4



###
GET http://localhost:4000/124
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxN2RkZjFkLWYwNzMtNGI5Ni1iMzdiLTdlMWI0NTVjMjc0OCIsImZpcnN0bmFtZSI6IkVyaWNhIiwibGFzdG5hbWUiOiJlcmljYSIsImVtYWlsIjoid2FuQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU2Nzg5IiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY3MjkyNTQzNywiZXhwIjoxNjczMDExODM3fQ.OeydOe5p9lLoNj7tVN1GYASoiktmXNDYrKT5NBE7Ng4


###
GET http://localhost:4000/users/ec11242e-8203-427f-8ef8-236a47bb0307/parcels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxN2RkZjFkLWYwNzMtNGI5Ni1iMzdiLTdlMWI0NTVjMjc0OCIsImZpcnN0bmFtZSI6IkVyaWNhIiwibGFzdG5hbWUiOiJlcmljYSIsImVtYWlsIjoid2FuQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU2Nzg5IiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY3MjkyNTQzNywiZXhwIjoxNjczMDExODM3fQ.OeydOe5p9lLoNj7tVN1GYASoiktmXNDYrKT5NBE7Ng4

###
GET http://localhost:4000/users/ec11242e-8203-427f-8ef8-236a47bb0307/parcels/sent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxN2RkZjFkLWYwNzMtNGI5Ni1iMzdiLTdlMWI0NTVjMjc0OCIsImZpcnN0bmFtZSI6IkVyaWNhIiwibGFzdG5hbWUiOiJlcmljYSIsImVtYWlsIjoid2FuQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU2Nzg5IiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY3MjkyNTQzNywiZXhwIjoxNjczMDExODM3fQ.OeydOe5p9lLoNj7tVN1GYASoiktmXNDYrKT5NBE7Ng4
###
GET http://localhost:4000/users/ec11242e-8203-427f-8ef8-236a47bb0307/parcels/received
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxN2RkZjFkLWYwNzMtNGI5Ni1iMzdiLTdlMWI0NTVjMjc0OCIsImZpcnN0bmFtZSI6IkVyaWNhIiwibGFzdG5hbWUiOiJlcmljYSIsImVtYWlsIjoid2FuQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU2Nzg5IiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTY3MjkyNTQzNywiZXhwIjoxNjczMDExODM3fQ.OeydOe5p9lLoNj7tVN1GYASoiktmXNDYrKT5NBE7Ng4